### ISSUE TITLE
Interstellar Assembly Selection

### ISSUE THREAD

**Issue by Haykii03** [jinxOAO/DSPmod_MoreMegaStructures#11]
Hello, I have a bug today where when I want to select Assembly mode in the (Y) menu, it fails and ask me to report. It's seems to be linked with the starIndex as I'm using GS2 in my game. I see in your code that your for loop stop at index 100, and I have more than 100 stars in my galaxy setup. Is this a bug? Or this allow for memory saving maybe? (As I see List of List for this MegaStructure). Should I try to locate a star with a Index of 100 or less? Or this won't solve my problem? Maybe extend the loops to 1000? Idk :)

Thx for your work, this mod is super good for late game content !

**Comment by Haykii03** [comment]
I go to the middle of the map and manage to found a star with ID <100 and it seems to be working :)

**Comment by jinxOAO** [comment]
I once considered that the operating efficiency and saving/loading might be slowed down by the larger number of galaxies, but in fact there may not be a significant difference. I may try to offer the option of 1000 starindex to the player in a future version, if my tests show that it really doesn't affect the game speed.

**Comment by GabrielBallardin** [comment]
> 

are you crazy man? How do you put a limitation like this in the game and not inform this in the description? I played for over 100 hours to get to the mega structures to get a warning that only "seed" is supported with 100 systems? For the love of god, man, fix this as soon as possible. if it's going to cause slowdowns, fuck the player, each with their own problems. but the game cannot limit construction.

![image](https://user-images.githubusercontent.com/58851234/224405239-54693921-d6a8-4ed4-baf6-1abc1d51ccb1.png)

**Comment by jinxOAO** [comment]
> > 
> 
> are you crazy man? How do you put a limitation like this in the game and not inform this in the description? I played for over 100 hours to get to the mega structures to get a warning that only "seed" is supported with 100 systems? For the love of god, man, fix this as soon as possible. if it's going to cause slowdowns, fuck the player, each with their own problems. but the game cannot limit construction.
> 
> ![image](https://user-images.githubusercontent.com/58851234/224405239-54693921-d6a8-4ed4-baf6-1abc1d51ccb1.png)

I've updated that, now it'll support 1000 star systems. Set up to 1024 stars is a little troublesome and there might be problems when reading and writing old archives that I can’t quickly complete the test, so I hope you are lucky enough that you've chosen a star system with a index less that 1000. Good news is, if you load the game and see the chosen of megastructure type maintains interstellar assembly, that means its index is less than 1000.
