### ISSUE TITLE
集成组件产出速度显示问题

### ISSUE THREAD

**Issue by qiankaihua** [jinxOAO/DSPmod_MoreMegaStructures#12]
巨构界面显示0.35/min，但是实际上大约在20+分钟才会产出一个，预估速度差距十倍，这个是否可以统一一下显示和实际产出？
最开始用速度慢的时候会疑惑是不是自己用法错误了

**Comment by jinxOAO** [comment]
可能是你（默认）打开了远程接收到背包的功能？这会使效率降低到1/10。
此外，大概几个版本前有显示数值和实际数值差60倍的问题，但是如果你是最新版本，那就应该不是这个原因。

**Comment by qiankaihua** [comment]
> 



> 可能是你（默认）打开了远程接收到背包的功能？这会使效率降低到1/10。 此外，大概几个版本前有显示数值和实际数值差60倍的问题，但是如果你是最新版本，那就应该不是这个原因。

是的，确实是接收到背包的问题，感觉可以更新下README？因为我没有找到相关的说明

**Comment by andrewtranter** [comment]
how do I change this?
they are teleported to my inventory and I cant stop it.

**Comment by jinxOAO** [comment]
> how do I change this? they are teleported to my inventory and I cant stop it.

press 'C' , in mecha UI, you can see a Remote-Teleport Multifunction Component Upper Limit option, set it to OFF.

**Comment by andrewtranter** [comment]
thankyou I found it! I didnt notice the new menu there.
