### ISSUE TITLE
圣遗物是否加成星际组装厂

### ISSUE THREAD

**Issue by stat0s2p** [jinxOAO/DSPmod_MoreMegaStructures#14]
我安装了另外一个mod [DSP_Battle](https://github.com/ckcz123/DSP_Battle)，里面有些加成效果能在对应生产建筑生产产物时返回原料。
请问如DSP_Battle中 _蓝buff_ ， _女神之泪_ ， _能量迸发_ 这样返还原料的 _圣遗物_ 效果对 _星际组装厂_ 的配方有加成效果吗？

**Comment by jinxOAO** [comment]
对星际组装厂没有效果
