### ISSUE TITLE
Broken ?

### ISSUE THREAD

**Issue by Tocksson** [jinxOAO/DSPmod_MoreMegaStructures#19]
![image](https://github.com/jinxOAO/DSPmod_MoreMegaStructures/assets/141529880/1e4c4d51-f375-4e94-b026-0dab192a2351)

**Comment by jinxOAO** [comment]
This mod is currently broken. I'm working on it right now, and I might upload a fixed version this weekend if things go smoothly.

**Comment by Tocksson** [comment]
cool, thx jinx
