### ISSUE TITLE
suggestion:Interstellar Assembly ease of use improvement suggestions

### ISSUE THREAD

**Issue by 32star98** [jinxOAO/DSPmod_MoreMegaStructures#22]
当前版本v1.2.1只有能量分配滑动条，
建议增加产量控制选项，因为星际组装厂正在建设中的时候也会使用，但有些原料输入量有限
建议增加数值输入选项，滑动不好量化控制

**Comment by 32star98** [comment]
增产中间产物和输出优化：
比如想同时输出绿马达和蓝马达时，如果物资交换站设置了这两项，绿马达作为中间产物没有喷涂，则蓝马达增产效果失去，希望增加一个自动喷涂功能，或者允许限制物资交换站物品流动方向，明确输入输出

**Comment by jinxOAO** [comment]
好的，我看看能不能后续增加一个限制生产速度上限的输入框。
中间产物是这样的，因为暂存在星际组装厂内部的中间产物视为已喷涂3级增产，但是送到地面交换站就消失了。所以如果不需要中间产物输出到地面可以不在物资交换站预留中间产物的位置。就算已经预留（比如中间产物也需要送到地面有别的用处），那么如果交换站满了的话，产物还会溢出暂存在星际组装厂内部仓储里，内部仓储里的材料是被优先消耗的应该是也按3级增产材料计算的，所以需要把中间产物的生产速度调整到比需要的略微高一些，保证他能溢出到内部仓储（调低交换站的储存上限也是一个选择）。

**Comment by 32star98** [comment]
好的，感谢答复。
