### ISSUE TITLE
Compatibility with certain mods has been lost

### ISSUE THREAD

**Issue by nomeimei** [jinxOAO/DSPmod_MoreMegaStructures#27]
MoreMegaStructure : 1.3.1
GenesisBook : 2.9.10
DSP : 0.10.29.21904

MoreMegaStructure gained compatibility with GenesisBook in version 1.1.9, but now appears to have lost it.
An error occurs during the process of launching and initialising (loading) the game, and the game cannot be played.
Is there any way to resolve this?

```
NullReferenceException: Object reference not set to an instance of an object
ProjectGenesis.Utils.JsonDataUtils.PrefabDescPostFix ();(0)
ProjectGenesis.ProjectGenesis.PostAddDataAction ();(0)
xiaoye97.Patches.VFPreload_Patch.VFPreloadPrePatch ();(0)
VFPreload.InvokeOnLoadWorkEnded ();(0)
VFPreload+<PreloadThread>d__42.MoveNext ();(0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress);(0)
== Mod patches on the stack ==
InvokeOnLoadWorkEnded(Prefix): static void xiaoye97.Patches.VFPreload_Patch::VFPreloadPrePatch()
InvokeOnLoadWorkEnded(Postfix): static void xiaoye97.Patches.VFPreload_Patch::VFPreloadPostPatch()
InvokeOnLoadWorkEnded(Postfix): static void CommonAPI.VFPreloadPatch::OnMainMenuOpen()
InvokeOnLoadWorkEnded(Postfix): static void ProjectGenesis.Compatibility.InstallationCheckPlugin::OnMainMenuOpen()
InvokeOnLoadWorkEnded(Postfix): static void ProjectGenesis.Compatibility.MoreMegaStructure::LDBToolOnPostAddDataAction()
InvokeOnLoadWorkEnded(Postfix): static void ProjectGenesis.Patches.UI.HarmonyLogPatches::InvokeOnLoadWorkEnded()
InvokeOnLoadWorkEnded(Postfix): static void ProjectGenesis.Patches.Logic.DisableLDBToolCachePatches::DeleteFiles()
InvokeOnLoadWorkEnded(Postfix): static void FactoryLocator.Plugin::Init()
InvokeOnLoadWorkEnded(Postfix): static void DSPRecipeFinder.Main::VFPreload_InvokeOnLoadWorkEnded_Patch()
```

![image](https://github.com/jinxOAO/DSPmod_MoreMegaStructures/assets/40678604/b5d9acff-b364-4e6a-bf27-fb5936a22754)

**Comment by nomeimei** [comment]
Sorry, I'm sorry, I'm not sure how to fix this. There seems to have been a mistake on my part.
The actual incompatibility seemed to be with a mod called Nucleosynthesis, which depends on GenesisBook.
Nucleosynthesis : 1.2.1

I would like to play with both mods at the same time, are there any plans on the MoreMegaStructure side to support Nucleosynthesis?

Sorry if it sounds like I'm being selfish, but I'm commenting in the hope of good news.

**Comment by jinxOAO** [comment]
I'm sorry, bad news. I can't find out the reason and I don't know how to fix this. Btw the author of Nucleosynthesis said that he/she may not support or update that mod anymore, so I may not continue dealing with this problem. If removing Nucleosynthesis will fix this problem, I suggest you do this.
