### ISSUE TITLE
Interstellar Assembly Error Message

### ISSUE THREAD

**Issue by AefRal** [jinxOAO/DSPmod_MoreMegaStructures#29]
The error message goes away too quickly and is off screen, so I can't read the whole message. It says:
[Warning! This MegaStructure does not support the galaxy with more than 100 star systems. Please find a star system with Starindex...].

What comes after Starindex? I was able to select recipes earlier, closer to where I started, but those stars are low luminosity.
Is the assembly only able to be built on certain star types?

![20240205214156_1](https://github.com/jinxOAO/DSPmod_MoreMegaStructures/assets/68062495/3a15ff34-be7d-4f31-89e5-aa5ca6363934)

**Comment by jinxOAO** [comment]
If you are using GS2, find the MMS config file in BepInEx/config, then change the Support1000Stars to true. This will make the star assembly can be built in almost every star system.
