### ISSUE TITLE
2k屏戴森球界面左下的规划列表的检测范围有问题

### ISSUE THREAD

**Issue by sylarchmin** [jinxOAO/DSPmod_MoreMegaStructures#3]
鼠标移动到规划戴森球按钮的位置，弹出层认为鼠标已经移出弹出层，直接开始了收缩，导致切换为其他巨构后无法再点击切换回戴森球

**Comment by sylarchmin** [comment]
配置中不管配置true还是false都一样，版本是1.0.1

**Comment by sylarchmin** [comment]
是的，标准的2k
________________________________
发件人: jinx ***@***.***>
发送时间: 2022年5月4日 0:44
收件人: jinxOAO/DSPmod_MoreMegaStructures ***@***.***>
抄送: sylarchmin ***@***.***>; Author ***@***.***>
主题: Re: [jinxOAO/DSPmod_MoreMegaStructures] 2k屏戴森球界面左下的规划列表的检测范围有问题 (Issue #3)


分辨率是2k吗？

―

**Comment by jinxOAO** [comment]
原谅我先看的内容没看标题，后来才看到标题就删了（撤回失败。。。显得我有点蠢）。 anyway，尝试一下这个看看是否能行
https://github.com/jinxOAO/DSPmod_MoreMegaStructures/releases/tag/MMS1.0.2

**Comment by sylarchmin** [comment]
测试了，可以😁
________________________________
发件人: jinx ***@***.***>
发送时间: 2022年5月4日 1:17
收件人: jinxOAO/DSPmod_MoreMegaStructures ***@***.***>
抄送: sylarchmin ***@***.***>; Author ***@***.***>
主题: Re: [jinxOAO/DSPmod_MoreMegaStructures] 2k屏戴森球界面左下的规划列表的检测范围有问题 (Issue #3)


原谅我先看的内容没看标题，后来才看到标题就删了（撤回失败。。。显得我有点蠢）。 anyway，尝试一下这个看看是否能行
https://github.com/jinxOAO/DSPmod_MoreMegaStructures/releases/tag/MMS1.0.2

**Comment by jinxOAO** [comment]
ok我稍后会在网站上更新的

**Comment by sylarchmin** [comment]
哈，好像这个有新问题，Y界面是可以了，制造面板中巨构面板中是空的，我使用Auxilary functions mod在新存档中试过的
另外我是R2中1.0.1 disabled然后install local mod方式加载的，不知道是不是这样会有问题
________________________________
发件人: jinx ***@***.***>
发送时间: 2022年5月4日 1:21
收件人: jinxOAO/DSPmod_MoreMegaStructures ***@***.***>
抄送: sylarchmin ***@***.***>; Author ***@***.***>
主题: Re: [jinxOAO/DSPmod_MoreMegaStructures] 2k屏戴森球界面左下的规划列表的检测范围有问题 (Issue #3)


ok我稍后会在网站上更新的

―

**Comment by jinxOAO** [comment]
老存档也是空的吗？

**Comment by sylarchmin** [comment]
是的，我本来是直接打开老的看的，看空的，以为可能是老存档的原因，然后退出去新建存档，解锁全部科技，看到就是空的，还大退过一次试了下
________________________________
发件人: jinx ***@***.***>
发送时间: 2022年5月4日 1:29
收件人: jinxOAO/DSPmod_MoreMegaStructures ***@***.***>
抄送: sylarchmin ***@***.***>; Author ***@***.***>
主题: Re: [jinxOAO/DSPmod_MoreMegaStructures] 2k屏戴森球界面左下的规划列表的检测范围有问题 (Issue #3)


老存档也是空的吗？

―

**Comment by jinxOAO** [comment]
你试一下用这个zip，主要是刚才我只发了dll，缺少了mmstabicon这个图标文件，我猜是因为这个。
https://github.com/jinxOAO/DSPmod_MoreMegaStructures/releases/tag/MMS1.0.2
（你把原本mod文件夹里的mmstabicon文件复制到你新的dll同文件夹下也一样）。

**Comment by sylarchmin** [comment]
嗯，可以了，新老存档终于又正常了
________________________________
发件人: jinx ***@***.***>
发送时间: 2022年5月4日 1:37
收件人: jinxOAO/DSPmod_MoreMegaStructures ***@***.***>
抄送: sylarchmin ***@***.***>; Author ***@***.***>
主题: Re: [jinxOAO/DSPmod_MoreMegaStructures] 2k屏戴森球界面左下的规划列表的检测范围有问题 (Issue #3)


你试一下用这个zip，主要是刚才我只发了dll，缺少了mmstabicon这个图标文件，我猜是因为这个。
https://github.com/jinxOAO/DSPmod_MoreMegaStructures/releases/tag/MMS1.0.2
（你把原本mod文件夹里的mmstabicon文件复制到你新的dll同文件夹下也一样）。

―
