### ISSUE TITLE
[Star Cannon] Target the hives in space?

### ISSUE THREAD

**Issue by Teck1015** [jinxOAO/DSPmod_MoreMegaStructures#35]
Am I using the Star Cannon incorrectly? Is there any way to make the Star Cannon destroy the Dark Fog Hives orbiting the stars in other systems, or does it only destroy the Dark Fog Bases & Relays on Planets?

Currently, my Star Cannon is only Stage 1, so is the damage too low to be able to do that?

Thank you in advance.

**Comment by jinxOAO** [comment]
Actually the star cannon can only attacking the space unit(including space hives orbiting a star, space relays and planet relays) .

**Comment by Teck1015** [comment]
Oh okay. Does it need to do more damage to destroy a hive? Mine is only Stage 1 and it's only destroying Relays.

**Comment by jinxOAO** [comment]
The star cannon's target selection logic has nothing to do with its damage by principle. It depends on how the enemies are arranged in the enemyPool. It might choose the relays first, and, before it can switch to next hive target, it use up all its fire time. So in this way, higher damage may help it to select the hive targets.

**Comment by Teck1015** [comment]
I see. Thank you! I will try that. It is also far away and I know the cannon loses damage per light year.
