### ISSUE TITLE
在游戏内会无限增加Output_Log的文件大小

### ISSUE THREAD

**Issue by Leng-Long** [jinxOAO/DSPmod_MoreMegaStructures#37]
文件位于C:\Users\Administrator\AppData\LocalLow\Youthcat Studio\Dyson Sphere Program\output_log.txt
联机时发现c盘空间异常才注意到的 那时候log已经209G大小了(草
![QQ截图20240622034303](https://github.com/jinxOAO/DSPmod_MoreMegaStructures/assets/173502119/3f6069e5-a2ff-4e27-a51a-ef08913bb687)
mod一共启用这些
![QQ截图20240622034326](https://github.com/jinxOAO/DSPmod_MoreMegaStructures/assets/173502119/762a3104-3c35-4273-89e6-ffd39ae543f3)
该文件内刷屏的内容（mulit Thread enable with 0）
已经排查了存档与mod冲突问题（指单启用该mod与开新档都仍然存在该bug）
不清楚是不是只有我这样 反正我联机的另一个人那边的output也出现了该问题。

**Comment by starfi5h** [comment]
MoreMegaStructures v1.5.0的打印造成的
```cs
[HarmonyPostfix]
[HarmonyPatch(typeof (WorkerThreadExecutor), "ComputerThread")]
public static void CTest(WorkerThreadExecutor __instance) => Utils.Log(string.Format("multi Thread enabled with {0}", (object) (uint) __instance.threadMissionOrders));
```

**Comment by Leng-Long** [comment]
好问题。所以这个怎么解决呢（）
禁用之后不知道哪个mod抽风 导致保存会出现修改数据的提示
![QQ图片20240622142928](https://github.com/jinxOAO/DSPmod_MoreMegaStructures/assets/173502119/83971464-6388-4285-bb31-eaaf61493b59)
（然后整了屏蔽异常检测玩的）

**Comment by jinxOAO** [comment]
收到，我立刻更新一下。

**Comment by jinxOAO** [comment]
数据异常是正常现象，是因为mod把游戏内数据修改了。
