### ISSUE TITLE
恒星炮充能时间异常

### ISSUE THREAD

**Issue by Seraph007** [jinxOAO/DSPmod_MoreMegaStructures#42]
使用恒星炮，为什么充能时间出错了，不是20分钟，变成了如图时间，这个怎么解决啊
![20240902033923_1](https://github.com/user-attachments/assets/d9034d57-9159-42e7-95cc-d9b3bde91006)

**Comment by jinxOAO** [comment]
如果你在用深空来敌mod，尝试按键q1597531q打开控制台输入cool回车临时解决一下。后续看看还会不会重复出现这种情况。
如果你没有在用深空来敌，就得等我更新一下，我今晚看看。目前不知道出现的原因，只能后续加一个倒计时最大值判断。

**Comment by Seraph007** [comment]
确实用了深空来敌，之前把炮拆了重新造的，目前玩下来没有复现这个情况
