### ISSUE TITLE
Interstaller Assembler not compatible with galaxy of more than 100 stars?

### ISSUE THREAD

**Issue by Umbrasong** [jinxOAO/DSPmod_MoreMegaStructures#43]
I have, previously in this save, built one of almost every specialization for the Interstellar assembler, with the exception of the deuterium/antimatter fuel one.  I finally got around to creating this, and I could set the sphere type, create the struts and shells...

but as soon as I attempt to set a recipe, I get an floating tooltip (that disappears in about 3 seconds) that I believe reads "This Structure Type not compatible with galaxies over 100 stars".  Is this a recent change (since the last time I created an interstellar assembler)? or is something else going on? and is there any other data you want/need?

**Comment by jinxOAO** [comment]
There should not be any risks. But I suggest backup your save first. Then turn the support 1000 stars to true in config file. 

It is not a recent change. Actually it was a flaw in very old versions that I didn't think of players could have a save with more than 64 stars.

**Comment by jinxOAO** [comment]
But if you are playing a save with more than 1000 stars. Even with the config changed, there is still a very small chance that you will choose a star with a star index greater than 1000 (usually located at the edge of the galaxy), making it impossisble to set its megastructure type. In that case, the only solution is to find another star.
