### ISSUE TITLE
No recipes

### ISSUE THREAD

**Issue by darkternal** [jinxOAO/DSPmod_MoreMegaStructures#44]
I can not craft any mod ray reciever - there is no any recipe avaiable (all other mod items are craftable). Also Interstellar Assembly not working and there is "Energy Allocation: 0%" note above each recipe.
![1](https://github.com/user-attachments/assets/bb91f9fc-5e50-443a-a8d0-58fb33d376ee)
![2](https://github.com/user-attachments/assets/4300cf1e-6adf-4ab3-b1e4-6b53cd709b43)

**Comment by jinxOAO** [comment]
MMS Receivers are already removed. You should only use the vanilla receivers, whose mode can be changed in its UI Panel.

As for the energy allocation, please click or drag the bar under the text "Energy Allocation 0%", to change the enegy manually.

**Comment by darkternal** [comment]
Thanks and sorry fo my stupidity:)
