### ISSUE TITLE
Make specialty receivers upgradable form regular receiver 

### ISSUE THREAD

**Issue by pobwarrior** [jinxOAO/DSPmod_MoreMegaStructures#6]
I was trying to use the BlueprintTweaks mod to modify some receiver blueprints and noticed the moremegastructure receivers couldn't be swapped out from a ray receiver, so I reached out to the mod maker of BlueprintTweaks to see what could be done

"[9:18 PM] Kremnev8: Probably has something to do with them not being upgrade able to one another. I think that's how I check that.
[10:33 PM] andromansis: So if the mod maker makes it upgradable then it should work?
[10:34 PM] Kremnev8: Probably."

Here is the mod in question : https://dsp.thunderstore.io/package/kremnev8/BlueprintTweaks/

and here is the specific behavior that this would enable : https://raw.githubusercontent.com/kremnev8/DSP-Mods/master/Mods/BlueprintTweaks/recipe-preview.gif

**Comment by jinxOAO** [comment]
I've make those receivers upgradable, it might work now (not tested yet).
